services:

  # NGINX
  nginx:
    container_name: nginx
    image: debian:12-slim
    ports:
      - "443:443"
    build:
      dockerfile: ./requirements/nginx/Dockerfile

  # MARIADB
  mariadb:
    container_name: mariadb
    image: debian:12-slim
    ports:
      - "3306:3306"
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
      
  # WORDPRESS

  wordpress:
    container_name: wordpress
    image: debian:12-slim
    ports:
      - "9000:9000"
    build:
      dockerfile: ./requirements/wordpress/Dockerfile
