services:
  nginx:
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
    - inception
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    networks:
    - inception
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - credential
      - db_password
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:
    driver: bridge
    
secrets:
  credential:
    file: ../secrets/credential.txt
  db_password: 
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

volumes: 
  mariadb:
    driver_opts:
      type: none
      o: bind
      device: /home/$USERNAME/data/mariadb
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /home/$USERNAME/data/wordpress