services:

  # NGINX
  nginx:
    container_name: nginx
    image: nginx:custom
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    # data
    volumes:
     - wordpress_data:/var/www/html:ro
    env_file:
      - .env
    # network
    networks:
      - inception
    ports:
      - "443:443"

  # MARIADB
  mariadb:
    container_name: mariadb
    image: mariadb:custom
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: unless-stopped
    # data
    env_file:
      - .env
    # network
    networks:
      - inception
      
  # WORDPRESS
  wordpress:
    container_name: wordpress
    image: wordpress:custom
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: unless-stopped
    # data
    env_file:
      - .env
    # network
    networks:
      - inception

# shared network for all container
networks:
  inception:
    driver: bridge

# shared storage
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vbox/data/wordpress

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vbox/data/mariadb